# Prettier configuration for GhondiClaude.tech

# Basic formatting
semi: true
singleQuote: true
trailingComma: es5
tabWidth: 2
useTabs: false

# JavaScript/TypeScript
arrowParens: avoid
quoteProps: as-needed
bracketSpacing: true
bracketSameLine: false

# JSX
jsxSingleQuote: false
jsxBracketSameLine: false

# Line length
printWidth: 80
proseWrap: preserve

# End of line
endOfLine: lf

# Plugin-specific settings
tailwindConfig: ./tailwind.config.js
plugins:
  - prettier-plugin-tailwindcss

# File-specific overrides
overrides:
  - files: '*.md'
    options:
      proseWrap: always
      printWidth: 100
  - files: '*.json'
    options:
      printWidth: 120
